### ISSUE TITLE
Possiblity to Port for 2010?

### ISSUE THREAD

**Issue by kilasuit** [inclinetechnical/QuickCAML#3]
Loving the look of this (although not tested yet)

Is this something that would this be possible for 2010 as well?

**Comment by inclinetechnical** [comment]
Quite possibly. SharePoint 2010's client-side object model isn't as robust as 2013's, so I'll need to look at that in more detail and see how closely a 2010 port would resemble the functionality of the 2013 version.

**Comment by kilasuit** [comment]
I did quickly look at this earlier on and did almost get it working.

Will look into more this weekend and push change with a new .aspx page for 2010

**Comment by inclinetechnical** [comment]
Sounds good!

**Comment by kilasuit** [comment]
This should be complete with the Pull request i've submitted

**Comment by inclinetechnical** [comment]
Got it - merged in. Thanks!
