### ISSUE TITLE
List View Threshold Error

### ISSUE THREAD

**Issue by jagrock** [inclinetechnical/QuickCAML#7]
For lists with more than 5000 lines, you will get the below error.  Setting the page size in the Cog menu does not seem to be working.  I've tried several options below 5000 (1000 is what i use in other tools) but it's not working.  Not sure if it should be added to the XML or not, as not that familar with CAML and the other query tool I use is the SharePointPnPOnline PowerShell module.  It's cmdlet has a PageSize parameter.

Error:
The request failed.

The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator.
![2018-12-17 18_53_51-smartcaml v 2 2 0 0](https://user-images.githubusercontent.com/790412/50125120-22ac1e80-022d-11e9-827c-e40f7d3d4365.png)

**Comment by sapientcoder** [comment]
I think you've got the wrong CAML tool... the screen shot you posted says "SmartCAML," and this tool is called "QuickCAML" and wouldn't show a Windows desktop popup like that since it's a web-based tool.
